In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [2]:
import torch

In [3]:
#Create 5 row 3 column
x = torch.empty(5,3)
x

tensor([[-2.3510e-22,  4.5572e-41, -2.3510e-22],
        [ 4.5572e-41, -3.5484e-24,  4.5572e-41],
        [ 1.3091e+16,  4.5572e-41,  3.8674e+19],
        [ 4.5572e-41, -3.3232e-24,  4.5572e-41],
        [ 1.3034e+16,  4.5572e-41, -2.3013e-23]])

In [4]:
#Create random 5 row 3 column for 0 - 1
x = torch.rand(5,3)
x

tensor([[0.2920, 0.3801, 0.2267],
        [0.9088, 0.9944, 0.6325],
        [0.0034, 0.7182, 0.5990],
        [0.4184, 0.6178, 0.9693],
        [0.0347, 0.1782, 0.7659]])

In [5]:
#Define data type
x = torch.zeros(5,3, dtype=torch.long)
x

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [6]:
#Create by Tensor
x = torch.Tensor(5,3)
x

tensor([[-2.3510e-22,  4.5572e-41, -2.3510e-22],
        [ 4.5572e-41,  9.3719e-01,  4.5572e-41],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00]])

In [7]:
#Create data with me by Tensor
x = torch.Tensor([5,3])
x

tensor([5., 3.])

In [8]:
#Create all is 1
x = torch.ones(5,3)
x

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [9]:
#Create y have row and column such as x. I use randn_like
y = torch.randn_like(x, dtype=torch.double)
y

tensor([[-1.0027,  1.2768, -0.1535],
        [-1.0141,  2.3629, -1.4121],
        [ 1.0957, -0.1019, -1.2582],
        [ 0.5283, -0.6532, -0.7143],
        [-0.2482,  0.7147, -0.7318]], dtype=torch.float64)

In [10]:
#View size
y.shape #method 1
y.size() #method 2

torch.Size([5, 3])

**Add 2 data**

In [11]:
x

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [12]:
y = torch.rand(5, 3)
y

tensor([[0.5036, 0.2761, 0.4587],
        [0.6824, 0.7255, 0.8714],
        [0.7065, 0.7505, 0.0136],
        [0.2160, 0.0047, 0.6297],
        [0.2150, 0.9270, 0.2472]])

In [13]:
#Method 1
z = x + y
z

tensor([[1.5036, 1.2761, 1.4587],
        [1.6824, 1.7255, 1.8714],
        [1.7065, 1.7505, 1.0136],
        [1.2160, 1.0047, 1.6297],
        [1.2150, 1.9270, 1.2472]])

In [14]:
#Method 2
z = torch.add(x, y)
z

tensor([[1.5036, 1.2761, 1.4587],
        [1.6824, 1.7255, 1.8714],
        [1.7065, 1.7505, 1.0136],
        [1.2160, 1.0047, 1.6297],
        [1.2150, 1.9270, 1.2472]])

In [15]:
#Method 3
y.add_(x) # such as: y = y + x

tensor([[1.5036, 1.2761, 1.4587],
        [1.6824, 1.7255, 1.8714],
        [1.7065, 1.7505, 1.0136],
        [1.2160, 1.0047, 1.6297],
        [1.2150, 1.9270, 1.2472]])

In [16]:
a = torch.rand(4, 4)
a

tensor([[0.9414, 0.8667, 0.7233, 0.0304],
        [0.8719, 0.5252, 0.1275, 0.8548],
        [0.3583, 0.0315, 0.5535, 0.2586],
        [0.3778, 0.5371, 0.8863, 0.0557]])

In [17]:
b = torch.rand(4, 4)
b

tensor([[0.1003, 0.3748, 0.2683, 0.0954],
        [0.6054, 0.4379, 0.5873, 0.7259],
        [0.8980, 0.3823, 0.4349, 0.0919],
        [0.5187, 0.5136, 0.8111, 0.9769]])

In [18]:
#Method 4 (sum a and b)
c = torch.empty(4, 4)
torch.add(a,b,out=c)
c

tensor([[1.0417, 1.2415, 0.9916, 0.1258],
        [1.4773, 0.9631, 0.7148, 1.5806],
        [1.2563, 0.4138, 0.9884, 0.3505],
        [0.8965, 1.0507, 1.6974, 1.0326]])

In [19]:
#Get all row but get column 1
a[:, 1]

tensor([0.8667, 0.5252, 0.0315, 0.5371])

In [20]:
#Get row 0 and get column 1
a[0, 1]

tensor(0.8667)

In [21]:
#Get row 0-2 and get column 1
a[0:2, 1]

tensor([0.8667, 0.5252])

**Chang row and column data**

In [22]:
#Create x have 4 row and 4 column
x = torch.rand(4,4)
x.shape

torch.Size([4, 4])

In [23]:
#Change 4,4 to 1,16
x_update = x.view(16)
x_update.shape

torch.Size([16])

In [24]:
#Automatically divide row
x_update = x.view(-1, 8)
x_update.shape

torch.Size([2, 8])

**Get data**

In [25]:
x = torch.rand(1)
x

tensor([0.5155])

In [26]:
#Method 1
x.item()

0.5155229568481445

In [27]:
x_update

tensor([[0.1664, 0.2188, 0.0813, 0.1780, 0.4011, 0.2915, 0.9363, 0.5598],
        [0.2674, 0.2751, 0.2140, 0.2479, 0.1937, 0.7090, 0.0888, 0.3151]])

In [28]:
#Method 2
y = x_update.numpy() #Chang pytorch to numpy
y[0, 0]

0.16637594

In [29]:
#Method 3
a = np.ones(3)
a

array([1., 1., 1.])

In [30]:
#Method 3
b = torch.from_numpy(a)
b

tensor([1., 1., 1.], dtype=torch.float64)

**Use GPU**

In [31]:
device = torch.cuda.is_available()
device
#=> False, so haven't GPU

False

In [32]:
if torch.cuda.is_available():
    devide = torch.device("cuda")
    y = torch.ones_like(x, device=device)
    x = x.to(device)
    z = x + y
    print(z)

**Use CPU**

In [33]:
#chang gpu to cpu: cpu()
x.cpu()

tensor([0.5155])

# ***Torch.tensor***
1. requires_grad: 
- Nhắc nhở rằng mình có enable việc lưu trữ thông tin grad xuống không
- Có lưu thông tin gradien không?
2. grad_fn: 
- Đã sử dụng những hàm số nào
- Lưu thông tin hàm số đã được sử dụng của Tensor
3. backward(): hàm đạo hàm
4. grad: lưu các thông tin đạo hàm

In [34]:
x = torch.tensor(2.0, requires_grad=True)
x

tensor(2., requires_grad=True)

In [35]:
#Create y = e^x
y = torch.exp(x)
y

tensor(7.3891, grad_fn=<ExpBackward0>)

In [36]:
y.grad_fn

In [37]:
y.backward()
x.grad

tensor(7.3891)